"""clase 9

Revision ID: 8f1efcb570ee
Revises: 957eb23c2359
Create Date: 2026-09-28 10:02:37.738290

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f1efcb570ee'
down_revision: Union[str, Sequence[str], None] = '957eb23c2359'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_items_pedido_id'), table_name='items_pedido')
    op.drop_table('items_pedido')
    op.alter_column('pedidos', 'total',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=12, scale=2),
               nullable=False)
    op.alter_column('pedidos', 'estado',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pedidos', 'estado',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('pedidos', 'total',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.create_table('items_pedido',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('pedido_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('producto_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('cantidad', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('precio_unitario', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos.id'], name=op.f('items_pedido_pedido_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('items_pedido_pkey'))
    )
    op.create_index(op.f('ix_items_pedido_id'), 'items_pedido', ['id'], unique=False)
    # ### end Alembic commands ###
