"""usuarios con auth

Revision ID: 957eb23c2359
Revises: e6acfcbf65bf
Create Date: 2026-09-28 08:16:31.518233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '957eb23c2359'
down_revision: Union[str, Sequence[str], None] = 'e6acfcbf65bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'pedidos', 'usuarios', ['usuario_id'], ['id'])
    op.add_column('usuarios', sa.Column('acepto_tratamiento', sa.Boolean(), nullable=False))
    op.add_column('usuarios', sa.Column('fecha_consentimiento', sa.DateTime(timezone=True), nullable=False))
    op.alter_column('usuarios', 'rol',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usuarios', 'rol',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('usuarios', 'fecha_consentimiento')
    op.drop_column('usuarios', 'acepto_tratamiento')
    op.drop_constraint(None, 'pedidos', type_='foreignkey')
    # ### end Alembic commands ###
