"""add imagen_url to producto

Revision ID: 96e99454d1e4
Revises: 8665a8c81a0c
Create Date: 2026-09-28 11:44:20.186486

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '96e99454d1e4'
down_revision: Union[str, Sequence[str], None] = '8665a8c81a0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('productos', sa.Column('imagen_url', sa.String(), nullable=True))
    op.alter_column('usuarios', 'fecha_baja',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usuarios', 'fecha_baja',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_column('productos', 'imagen_url')
    # ### end Alembic commands ###
